FROM panchgonzalez/cudavision-base:latest

RUN pip install \
    cython \
    numba \
    pillow \
    imutils \
    scikit-learn \
    scikit-image \
    imageio \
    jupyter \
    kornia[x] \
    && pip install torch==1.10.0+cpu torchvision==0.11.1+cpu torchaudio==0.10.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html